services:
  mi-app-web:
    build: .
    container_name: app-comidas-orwin
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=comidas.orwinzavaleta.dpdns.org
      - VIRTUAL_PORT=80
    networks:
      - apps-net

networks:
  apps-net:
    external: true